version: "3.5"

services:
  frontend_dev:
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "9000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public